#!/bin/sh

/usr/bin/invoke_app "$@" -C @tool/bin/Mot2DDemoCC3D.sh -t mot2ddemocc3d \
                         -u compucell3d-4.4.0 \
                         -w captive \
                         -r none
